// ===== Categories =====
export const categories = [
    {
        id: "cat-1",
        name: "Men",
        slug: "men",
        description: "Premium menswear for the modern gentleman",
        image_url: "https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=600&q=80",
        sort_order: 1,
    },
    {
        id: "cat-2",
        name: "Women",
        slug: "women",
        description: "Elegant womenswear for every occasion",
        image_url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80",
        sort_order: 2,
    },
    {
        id: "cat-3",
        name: "Shoes",
        slug: "shoes",
        description: "Step up your game with luxury footwear",
        image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
        sort_order: 3,
    },
    {
        id: "cat-4",
        name: "Accessories",
        slug: "accessories",
        description: "Complete your look with premium accessories",
        image_url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
        sort_order: 4,
    },
    {
        id: "cat-5",
        name: "Activewear",
        slug: "activewear",
        description: "Performance meets style in our activewear line",
        image_url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
        sort_order: 5,
    },
    {
        id: "cat-6",
        name: "Outerwear",
        slug: "outerwear",
        description: "Weather the elements in style",
        image_url: "https://images.unsplash.com/photo-1544923246-77307dd270cb?w=600&q=80",
        sort_order: 6,
    },
];
// ===== Products =====
export const products = [
    {
        id: "prod-1",
        category_id: "cat-1",
        name: "Classic Leather Jacket",
        slug: "classic-leather-jacket",
        description: "A timeless leather jacket crafted from premium Italian lambskin. Features a tailored fit with ribbed cuffs and hem. The perfect statement piece for any wardrobe.",
        brand: "LUXE Originals",
        price: 299.99,
        compare_at_price: 449.99,
        stock_quantity: 15,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Brown"],
        rating: 4.8,
        review_count: 124,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-1", url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80", sort_order: 0, is_primary: true },
            { id: "img-1b", url: "https://images.unsplash.com/photo-1520975954732-35dd22299614?w=800&q=80", sort_order: 1, is_primary: false },
        ],
        created_at: "2025-01-15T10:00:00Z",
    },
    {
        id: "prod-2",
        category_id: "cat-2",
        name: "Silk Evening Dress",
        slug: "silk-evening-dress",
        description: "An exquisite silk evening dress in a stunning deep red. Features a flattering A-line silhouette with delicate draping. Perfect for galas, weddings, and special occasions.",
        brand: "Velvet Rose",
        price: 189.99,
        compare_at_price: 279.99,
        stock_quantity: 8,
        sizes: ["XS", "S", "M", "L"],
        colors: ["Red", "Black", "Navy"],
        rating: 4.9,
        review_count: 89,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-2", url: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80", sort_order: 0, is_primary: true },
            { id: "img-2b", url: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80", sort_order: 1, is_primary: false },
        ],
        created_at: "2025-02-01T10:00:00Z",
    },
    {
        id: "prod-3",
        category_id: "cat-3",
        name: "Urban Runner Sneakers",
        slug: "urban-runner-sneakers",
        description: "Minimalist white sneakers built for all-day comfort. Premium leather upper with cushioned insoles and a durable rubber outsole. From street to office.",
        brand: "StrideX",
        price: 149.99,
        compare_at_price: 199.99,
        stock_quantity: 22,
        sizes: ["7", "8", "9", "10", "11", "12"],
        colors: ["White", "Black", "Grey"],
        rating: 4.7,
        review_count: 256,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-3", url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80", sort_order: 0, is_primary: true },
            { id: "img-3b", url: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&q=80", sort_order: 1, is_primary: false },
        ],
        created_at: "2025-01-20T10:00:00Z",
    },
    {
        id: "prod-4",
        category_id: "cat-1",
        name: "Slim Fit Chino Pants",
        slug: "slim-fit-chino-pants",
        description: "Versatile slim-fit chino pants crafted from premium stretch cotton. A wardrobe essential that transitions effortlessly from casual to business casual.",
        brand: "LUXE Originals",
        price: 79.99,
        compare_at_price: 99.99,
        stock_quantity: 30,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Khaki", "Navy", "Olive", "Black"],
        rating: 4.5,
        review_count: 178,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-4", url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-03-01T10:00:00Z",
    },
    {
        id: "prod-5",
        category_id: "cat-2",
        name: "Cashmere Blend Sweater",
        slug: "cashmere-blend-sweater",
        description: "Luxuriously soft cashmere-wool blend sweater. Features a relaxed fit with ribbed trim. The ultimate in cozy sophistication.",
        brand: "Velvet Rose",
        price: 129.99,
        compare_at_price: undefined,
        stock_quantity: 18,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Cream", "Blush", "Grey", "Camel"],
        rating: 4.6,
        review_count: 67,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-5", url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-02-15T10:00:00Z",
    },
    {
        id: "prod-6",
        category_id: "cat-4",
        name: "Italian Leather Belt",
        slug: "italian-leather-belt",
        description: "Handcrafted Italian leather belt with a brushed gold buckle. A subtle statement of quality and refined taste.",
        brand: "Artisan Co.",
        price: 59.99,
        compare_at_price: 89.99,
        stock_quantity: 40,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Brown", "Tan"],
        rating: 4.4,
        review_count: 92,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-6", url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-01-10T10:00:00Z",
    },
    {
        id: "prod-7",
        category_id: "cat-5",
        name: "Performance Track Jacket",
        slug: "performance-track-jacket",
        description: "Lightweight technical jacket with moisture-wicking fabric and reflective details. Designed for runners and urban athletes who demand style and performance.",
        brand: "StrideX",
        price: 89.99,
        compare_at_price: 119.99,
        stock_quantity: 25,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Navy", "Charcoal"],
        rating: 4.3,
        review_count: 145,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-7", url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-03-10T10:00:00Z",
    },
    {
        id: "prod-8",
        category_id: "cat-6",
        name: "Wool Overcoat",
        slug: "wool-overcoat",
        description: "A distinguished double-breasted wool overcoat. Tailored with precision, featuring a notched lapel and deep pockets. The epitome of winter elegance.",
        brand: "LUXE Originals",
        price: 349.99,
        compare_at_price: 499.99,
        stock_quantity: 10,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Charcoal", "Camel", "Navy"],
        rating: 4.9,
        review_count: 56,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-8", url: "https://images.unsplash.com/photo-1544923246-77307dd270cb?w=800&q=80", sort_order: 0, is_primary: true },
            { id: "img-8b", url: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=800&q=80", sort_order: 1, is_primary: false },
        ],
        created_at: "2025-01-05T10:00:00Z",
    },
    {
        id: "prod-9",
        category_id: "cat-1",
        name: "Oxford Button-Down Shirt",
        slug: "oxford-button-down-shirt",
        description: "The quintessential oxford shirt in premium long-staple cotton. A perfectly relaxed collar with a clean finish. Essential for smart-casual dressing.",
        brand: "LUXE Originals",
        price: 69.99,
        compare_at_price: undefined,
        stock_quantity: 35,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Light Blue", "Pink", "Striped"],
        rating: 4.6,
        review_count: 203,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-9", url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-02-20T10:00:00Z",
    },
    {
        id: "prod-10",
        category_id: "cat-2",
        name: "High-Waisted Tailored Trousers",
        slug: "high-waisted-tailored-trousers",
        description: "Contemporary high-waisted trousers with a wide leg and crisp pleat. Made from fluid drape fabric for effortless movement.",
        brand: "Velvet Rose",
        price: 99.99,
        compare_at_price: 139.99,
        stock_quantity: 20,
        sizes: ["XS", "S", "M", "L"],
        colors: ["Black", "Beige", "Forest Green"],
        rating: 4.7,
        review_count: 78,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-10", url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-03-05T10:00:00Z",
    },
    {
        id: "prod-11",
        category_id: "cat-3",
        name: "Chelsea Leather Boots",
        slug: "chelsea-leather-boots",
        description: "Sleek Chelsea boots in supple calfskin leather with elasticated side panels. Goodyear welted for durability. A statement of refined masculinity.",
        brand: "Artisan Co.",
        price: 219.99,
        compare_at_price: 299.99,
        stock_quantity: 12,
        sizes: ["7", "8", "9", "10", "11", "12"],
        colors: ["Black", "Dark Brown"],
        rating: 4.8,
        review_count: 134,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-11", url: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-01-25T10:00:00Z",
    },
    {
        id: "prod-12",
        category_id: "cat-4",
        name: "Aviator Sunglasses",
        slug: "aviator-sunglasses",
        description: "Iconic aviator sunglasses with polarized lenses and titanium frames. UV400 protection with crystal-clear optics.",
        brand: "LUXE Originals",
        price: 159.99,
        compare_at_price: undefined,
        stock_quantity: 50,
        sizes: ["One Size"],
        colors: ["Gold/Green", "Silver/Blue", "Black/Grey"],
        rating: 4.5,
        review_count: 167,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-12", url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-02-10T10:00:00Z",
    },
    {
        id: "prod-13",
        category_id: "cat-5",
        name: "Yoga Leggings",
        slug: "yoga-leggings",
        description: "High-performance yoga leggings with four-way stretch and a seamless waistband. Buttery-soft fabric that moves with you.",
        brand: "StrideX",
        price: 64.99,
        compare_at_price: 89.99,
        stock_quantity: 0,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "Navy", "Burgundy", "Sage"],
        rating: 4.8,
        review_count: 312,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-13", url: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-03-15T10:00:00Z",
    },
    {
        id: "prod-14",
        category_id: "cat-6",
        name: "Quilted Puffer Jacket",
        slug: "quilted-puffer-jacket",
        description: "Lightweight yet incredibly warm quilted puffer. Features recycled down insulation and a water-resistant shell. Modern sustainability meets classic warmth.",
        brand: "LUXE Originals",
        price: 199.99,
        compare_at_price: 279.99,
        stock_quantity: 16,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Olive", "Burgundy"],
        rating: 4.6,
        review_count: 98,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-14", url: "https://images.unsplash.com/photo-1544923246-77307dd270cb?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-01-30T10:00:00Z",
    },
    {
        id: "prod-15",
        category_id: "cat-1",
        name: "Premium Denim Jeans",
        slug: "premium-denim-jeans",
        description: "Selvedge denim jeans in a modern slim fit. Japanese raw denim that develops a unique patina over time. For the denim connoisseur.",
        brand: "LUXE Originals",
        price: 119.99,
        compare_at_price: 159.99,
        stock_quantity: 28,
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Indigo", "Black", "Faded Blue"],
        rating: 4.7,
        review_count: 189,
        is_featured: true,
        is_active: true,
        images: [
            { id: "img-15", url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-02-25T10:00:00Z",
    },
    {
        id: "prod-16",
        category_id: "cat-4",
        name: "Leather Crossbody Bag",
        slug: "leather-crossbody-bag",
        description: "Compact crossbody bag in pebbled leather with an adjustable strap. Multiple compartments for everyday essentials.",
        brand: "Artisan Co.",
        price: 139.99,
        compare_at_price: 189.99,
        stock_quantity: 14,
        sizes: ["One Size"],
        colors: ["Camel", "Black", "Burgundy"],
        rating: 4.4,
        review_count: 76,
        is_featured: false,
        is_active: true,
        images: [
            { id: "img-16", url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80", sort_order: 0, is_primary: true },
        ],
        created_at: "2025-03-20T10:00:00Z",
    },
];
// ===== Mock Users =====
export const mockUsers = [
    {
        id: "user-1",
        email: "admin@luxe.com",
        first_name: "Admin",
        last_name: "User",
        role: "admin",
        created_at: "2025-01-01T00:00:00Z",
    },
    {
        id: "user-2",
        email: "john@example.com",
        first_name: "John",
        last_name: "Doe",
        role: "user",
        created_at: "2025-01-15T00:00:00Z",
    },
];
// ===== Mock Orders =====
export const mockOrders = [
    {
        id: "order-1",
        user_id: "user-2",
        full_name: "John Doe",
        email: "john@example.com",
        phone: "+1 234 567 8900",
        address: "123 Style Ave",
        city: "New York",
        state: "NY",
        country: "US",
        zip_code: "10001",
        status: "delivered",
        subtotal: 449.98,
        shipping_cost: 0,
        tax: 36.0,
        total: 485.98,
        payment_method: "card",
        payment_status: "paid",
        items: [
            {
                id: "oi-1",
                order_id: "order-1",
                product_id: "prod-1",
                product_name: "Classic Leather Jacket",
                product_image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80",
                quantity: 1,
                size: "L",
                color: "Black",
                price_at_purchase: 299.99,
            },
            {
                id: "oi-2",
                order_id: "order-1",
                product_id: "prod-3",
                product_name: "Urban Runner Sneakers",
                product_image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
                quantity: 1,
                size: "10",
                color: "White",
                price_at_purchase: 149.99,
            },
        ],
        created_at: "2024-03-01T10:00:00Z",
    },
    {
        id: "order-2",
        user_id: "user-2",
        full_name: "John Doe",
        email: "john@example.com",
        phone: "+1 234 567 8900",
        address: "123 Style Ave",
        city: "New York",
        state: "NY",
        country: "US",
        zip_code: "10001",
        status: "processing",
        subtotal: 159.98,
        shipping_cost: 9.99,
        tax: 12.8,
        total: 182.77,
        payment_method: "card",
        payment_status: "paid",
        items: [
            {
                id: "oi-3",
                order_id: "order-2",
                product_id: "prod-2",
                product_name: "Premium Denim Jeans",
                product_image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80",
                quantity: 2,
                size: "32",
                color: "Blue",
                price_at_purchase: 79.99,
            },
        ],
        created_at: "2024-03-10T15:30:00Z",
    },
];
// ===== Mock Addresses =====
export const mockAddresses = [
    {
        id: "addr-1",
        user_id: "user-2",
        label: "Home",
        full_name: "John Doe",
        phone: "+1 234 567 8900",
        street: "123 Fashion Avenue",
        city: "New York",
        state: "NY",
        zip_code: "10001",
        country: "United States",
        is_default: true,
    },
    {
        id: "addr-2",
        user_id: "user-2",
        label: "Office",
        full_name: "John Doe",
        phone: "+1 234 567 8900",
        street: "456 Business Blvd, Suite 100",
        city: "New York",
        state: "NY",
        zip_code: "10016",
        country: "United States",
        is_default: false,
    },
];
// ===== Helper functions =====
export function getProductsByCategory(categorySlug) {
    const category = categories.find((c) => c.slug === categorySlug);
    if (!category)
        return [];
    return products.filter((p) => p.category_id === category.id && p.is_active);
}
export function getProductBySlug(slug) {
    return products.find((p) => p.slug === slug && p.is_active);
}
export function getFeaturedProducts() {
    return products.filter((p) => p.is_featured && p.is_active);
}
export function searchProducts(query) {
    const q = query.toLowerCase();
    return products.filter((p) => p.is_active &&
        (p.name.toLowerCase().includes(q) ||
            p.brand.toLowerCase().includes(q) ||
            p.description.toLowerCase().includes(q)));
}
export function getAllBrands() {
    return [...new Set(products.map((p) => p.brand))];
}
export function getAllColors() {
    return [...new Set(products.flatMap((p) => p.colors))];
}
export function getAllSizes() {
    return [...new Set(products.flatMap((p) => p.sizes))];
}
