-- 1. ADD MISSING COLUMNS FIRST
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL'],
ADD COLUMN IF NOT EXISTS colors TEXT[] DEFAULT ARRAY['Classic Beige', 'Midnight Black', 'Ivory'];

-- 2. NOW UPDATE THE NAMES AND DETAILS
-- UPDATE MEN'S PRODUCTS
UPDATE products SET name = 'Oxford Slim Blazer', description = 'Hand-tailored in Italian wool. A sharp, structured silhouette designed for the modern gentleman.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Charcoal','Navy','Espresso'] WHERE id = 'm1';
UPDATE products SET name = 'Heritage Wool Coat', description = 'Double-faced merino wool coat with a clean dropped shoulder. Warmth without compromise.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Camel','Midnight','Stone'] WHERE id = 'm2';
UPDATE products SET name = 'Midnight Tuxedo', description = 'Peak lapel evening tuxedo cut from premium wool-silk blend. The pinnacle of formal dressing.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Black','Midnight Blue','White'] WHERE id = 'm3';
UPDATE products SET name = 'Savile Row Suit', description = 'Full-canvas construction meets razor-sharp tailoring. Handcrafted with British tweed.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Charcoal','Brown Herringbone','Grey'] WHERE id = 'm4';
UPDATE products SET name = 'Classic Trench Coat', description = 'The timeless trench, revisited. Waterproof gabardine with horn buttons and a belted waist.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Khaki','Black','Tan'] WHERE id = 'm5';
UPDATE products SET name = 'Italian Knit Sweater', description = 'Fine-gauge merino knit from the mills of Biella. Effortlessly elegant for any occasion.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Ivory','Forest Green','Burgundy'] WHERE id = 'm6';
UPDATE products SET name = 'Silk Evening Shirt', description = 'Woven from 100% Mulberry silk. The shirt that elevates every black-tie occasion.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['White','Pale Blue','Champagne'] WHERE id = 'm7';
UPDATE products SET name = 'Modern Slim Chino', description = 'Slim-cut chino with a stretch-comfort twill. Sophisticated enough for boardrooms, easy enough for weekends.', sizes = ARRAY['28','30','32','34','36'], colors = ARRAY['Sand','Slate','Olive'] WHERE id = 'm8';
UPDATE products SET name = 'Cashmere Cardigan', description = 'Grade-A Mongolian cashmere in a relaxed ribbed cut. Softer than anything you have worn before.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Oatmeal','Navy','Blush'] WHERE id = 'm9';
UPDATE products SET name = 'Urban Bomber Jacket', description = 'Satin-lined nylon shell with ribbed cuffs. Luxury street-wear for the discerning man.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Onyx','Olive Drab','Russet'] WHERE id = 'm10';
UPDATE products SET name = 'Alpine Parka', description = 'Down-filled technical parka with a water-resistant shell. Built for extreme style in any climate.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Forest','Black','Copper'] WHERE id = 'm11';
UPDATE products SET name = 'Minimalist Polo', description = 'Pique-knit mercerised cotton polo with ribbed collar. Clean lines, maximum impact.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Ecru','Sky','Port'] WHERE id = 'm12';
UPDATE products SET name = 'Double Breasted Vest', description = 'Six-button double-breasted waistcoat in fine wool. The perfect pairing for your dress trousers.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Charcoal','Burgundy','Black'] WHERE id = 'm13';
UPDATE products SET name = 'Checked Braces Blazer', description = 'Prince of Wales check blazer with contrast braces. Refined British country style for the city.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Brown Check','Grey Check','Navy Check'] WHERE id = 'm14';
UPDATE products SET name = 'Satin Peak Lapel Suit', description = 'Tonal satin peak lapels on a midnight wool base. Designed to be noticed without saying a word.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Midnight','Black','Steel Blue'] WHERE id = 'm15';
UPDATE products SET name = 'Corduroy Overshirt', description = 'Heavyweight corduroy shacket with hidden button placket. The perfect transitional layer.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Rust','Forest','Camel'] WHERE id = 'm16';
UPDATE products SET name = 'Linen Summer Blazer', description = 'Unlined washed linen blazer with patch pockets. Effortlessly relaxed for warm-weather occasions.', sizes = ARRAY['S','M','L','XL'], colors = ARRAY['Ivory','Sky Blue','Sand'] WHERE id = 'm17';

-- UPDATE WOMEN'S PRODUCTS
UPDATE products SET name = 'Silk Evening Gown', description = 'Floor-length bias-cut gown in pure Charmeuse silk. A masterpiece of feminine construction.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Champagne','Midnight','Rose'] WHERE id = 'w1';
UPDATE products SET name = 'Velvet Cocktail Dress', description = 'Stretch-velvet sheath with a fluted hem. Opulent texture meets modern silhouette.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Burgundy','Forest Green','Navy'] WHERE id = 'w2';
UPDATE products SET name = 'Cashmere Wrap Coat', description = 'Oversized double-cashmere wrap coat with a self-tie belt. Warmth embodied as pure luxury.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Camel','Ivory','Blush'] WHERE id = 'w3';
UPDATE products SET name = 'Floral Satin Slip Dress', description = 'Feminine, fluid, and powerful. Printed Charmeuse silk with adjustable straps.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Floral Print','Blush','Ivory'] WHERE id = 'w4';
UPDATE products SET name = 'Embroidered Gala Robe', description = 'Hand-embroidered floral motifs on a duchess satin base. Crafted for the grand occasion.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Gold','Ivory','Black'] WHERE id = 'w5';
UPDATE products SET name = 'Merino Knit Co-ord Set', description = 'Matching fine-knit crop top and wide-leg trousers. The co-ord that commands a room.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Ecru','Taupe','Blush'] WHERE id = 'w6';
UPDATE products SET name = 'Tailored Ivory Blazer', description = 'Power-shouldered single-breasted blazer in double-faced wool. Masculine structure, feminine grace.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Ivory','Chalk','Black'] WHERE id = 'w7';
UPDATE products SET name = 'Gold Belt Mini Dress', description = 'Structured ponte-knit mini with a sculpted gold chain belt. Day-to-night without a second look.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Black','Slate','Espresso'] WHERE id = 'w8';
UPDATE products SET name = 'Chiffon Layered Skirt', description = 'Multi-tiered georgette chiffon in a sweeping, movement-driven silhouette.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Lavender','Ivory','Sage'] WHERE id = 'w9';
UPDATE products SET name = 'Dramatic Opera Cloak', description = 'Full-length opera cape in heritage wool. The statement piece every wardrobe demands.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Black','Scarlet','Midnight Blue'] WHERE id = 'w10';
UPDATE products SET name = 'High Neck Lace Blouse', description = 'Victorian-inspired high-neck blouse in Chantilly lace. Romantic luxury refined for today.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Ivory','Black','Blush'] WHERE id = 'w11';
UPDATE products SET name = 'Pleated Midi Dress', description = 'Accordion-pleated satin midi with a deep V-neckline. Feminine poise in every step you take.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Copper','Silver','Navy'] WHERE id = 'w12';
UPDATE products SET name = 'Sequined Party Gown', description = 'Head-to-toe micro-sequin gown with a mermaid hem. Be impossible to ignore tonight.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Gold','Silver','Black'] WHERE id = 'w13';
UPDATE products SET name = 'Quilted Winter Coat', description = 'Channel-quilted down coat with a wool-cashmere exterior. British warmth, Italian soul.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Cocoa','Black','Blush'] WHERE id = 'w14';
UPDATE products SET name = 'Structured Corset Top', description = 'Boned satin corset top with heritage stitching. A celebration of the feminine form.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Black','Ivory','Champagne'] WHERE id = 'w15';
UPDATE products SET name = 'Minimalist Sheath Dress', description = 'Clean-cut crepe sheath with a subtle back slit. Supreme comfort. Zero compromises.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Black','Ivory','Caramel'] WHERE id = 'w16';
UPDATE products SET name = 'Bohemian Silk Maxi', description = 'Free-flowing printed silk maxi with a drawstring waist. Effortless beauty, every day.', sizes = ARRAY['XS','S','M','L'], colors = ARRAY['Paisley Print','Floral','Geometric'] WHERE id = 'w17';

-- UPDATE SHOES
UPDATE products SET name = 'Patina Leather Loafer', description = 'Hand-burnished calfskin with a distinctive patina finish. Italian craftsmanship at its very peak.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Cognac','Black','Dark Tan'] WHERE id = 's1';
UPDATE products SET name = 'Classic Brogue Oxford', description = 'Full-brogue wingtip in Scotch grain leather. The quintessential British gentleman''s shoe.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Dark Brown','Black','Burgundy'] WHERE id = 's2';
UPDATE products SET name = 'Grand Prix Sneaker', description = 'Tooled leather low-top with a cupsole. Where motorsport meets Milanese elegance.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['White','Black','Ecru'] WHERE id = 's3';
UPDATE products SET name = 'Velvet Evening Slipper', description = 'Embroidered velvet slipper with a gold chain ornament. Your most effortless evening shoe.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Midnight Blue','Bordeaux','Black'] WHERE id = 's4';
UPDATE products SET name = 'Chelsea Suede Boot', description = 'Pull-on suede Chelsea in a sleek square-toe cut. The one boot you will reach for every day.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Tan','Chocolate','Black'] WHERE id = 's5';
UPDATE products SET name = 'Midnight Monk Strap', description = 'Double monk-strap in mirror-polished calf leather. The pinnacle of business-formal footwear.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Black','Dark Brown','Oxblood'] WHERE id = 's6';
UPDATE products SET name = 'Italian Derby Shoe', description = 'Open-laced derby in buttery smooth nappa leather. Understated Italian school—perfectly executed.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Havana','Black','Stone Grey'] WHERE id = 's7';
UPDATE products SET name = 'Artisan Leather Sandal', description = 'Hand-stitched leather sandal with gold hardware buckles. Summer luxury, distilled.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Tan','Gold','Natural'] WHERE id = 's8';
UPDATE products SET name = 'Heritage Desert Boot', description = 'Crepe-soled suede desert boot in the original Clarks silhouette, elevated for Hamzure.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Sand','Chestnut','Black'] WHERE id = 's9';
UPDATE products SET name = 'Modernist Running Shoe', description = 'Technical knit upper on a sculptural foam sole. Athletic heritage, luxury finish.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['White/Grey','Black/Gold','Navy/Tan'] WHERE id = 's10';
UPDATE products SET name = 'Wingtip Spectator', description = 'Two-tone full-brogue spectator in contrasting calfskin. A shoe for those who appreciate art.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Black/White','Brown/Beige','Tan/White'] WHERE id = 's11';
UPDATE products SET name = 'Double Buckle Monk', description = 'Two wide buckle straps on a chisel-toe last. Sculptural hardware meets refined leather.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Black','Cognac','Antique Brown'] WHERE id = 's12';
UPDATE products SET name = 'Sleek Chelsea Boot', description = 'Razor-thin sole, pointed toe, elasticated sides. The most minimal Chelsea in our collection.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Matte Black','Oxide Brown','Bordeaux'] WHERE id = 's13';
UPDATE products SET name = 'Perforated Driver Shoe', description = 'Driving shoe meets Derby in a perforated calfskin upper. Weekend luxury done right.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Tan','Red','Navy'] WHERE id = 's14';
UPDATE products SET name = 'Silk Tassel Loafer', description = 'Hand-trimmed silk tassel loafer in Horween calfskin. A statement of quiet, confident luxury.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Cognac','Black','Bottle Green'] WHERE id = 's15';
UPDATE products SET name = 'Polished Cap Toe Oxford', description = 'Mirror-polished cap-toe in a clean, unadorned silhouette. The Oxford that defines all others.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Black','Dark Brown','Ox-Blood'] WHERE id = 's16';
UPDATE products SET name = 'Canvas Yacht Deck Shoe', description = 'Waxed canvas upper with hand-sewn construction. Built for the open sea. Worn for the city.', sizes = ARRAY['7','8','9','10','11','12'], colors = ARRAY['Navy/White','Tan/Cream','Ecru/Brown'] WHERE id = 's17';
